export const ActionTypes={
    FETCH_PRODUCTS:" FETCH_PRODUCTS",
    UPDATE_CART:"UPDATE_CART",
    SET_PRODUCTS:"SET_PRODUCTS",
    USER_NAME:"USER_NAME",
    PASSWORD:"PASSWORD",
    MAIL:"MAIL",
    SET_USER:"SET_USER",
    LOGIN_TOGGLE:"LOGIN_TOGGLE",
    SIGN_UP_TOGGLE:"SIGN_UP_TOGGLE",
    DELETE_CART_PRODUCT:"DELETE_CART_PRODUCT",
    INCREMENT_CART_PRODUCT:"INCREMENT_CART_PRODUCT",
    DECREMENT_CART_PRODUCT:"DECREMENT_CART_PRODUCT"
};